[2021-08-21 01:20:30,871] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-20T00:00:00+00:00 [queued]>
[2021-08-21 01:20:30,893] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-20T00:00:00+00:00 [queued]>
[2021-08-21 01:20:30,894] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:30,894] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:20:30,894] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:30,904] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-20T00:00:00+00:00
[2021-08-21 01:20:30,910] {standard_task_runner.py:52} INFO - Started process 11184 to run task
[2021-08-21 01:20:30,916] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-20T00:00:00+00:00', '--job-id', '11', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpdxg4fjhb', '--error-file', '/tmp/tmp3l3q_9_r']
[2021-08-21 01:20:30,916] {standard_task_runner.py:77} INFO - Job 11: Subtask is_api_available
[2021-08-21 01:20:30,967] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-20T00:00:00+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:20:31,040] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-20T00:00:00+00:00
[2021-08-21 01:20:31,040] {http.py:101} INFO - Poking: api/?nat=us,gb
[2021-08-21 01:20:31,050] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-21 01:20:31,052] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/?nat=us,gb
[2021-08-21 01:20:31,459] {base.py:248} INFO - Success criteria met. Exiting.
[2021-08-21 01:20:31,474] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210820T000000, start_date=20210821T012030, end_date=20210821T012031
[2021-08-21 01:20:31,525] {local_task_job.py:149} INFO - Task exited with return code 1
