[2021-08-21 01:20:29,984] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-20T00:00:00+00:00 [queued]>
[2021-08-21 01:20:30,007] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-20T00:00:00+00:00 [queued]>
[2021-08-21 01:20:30,007] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:30,007] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:20:30,008] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:20:30,020] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): creating_table> on 2021-08-20T00:00:00+00:00
[2021-08-21 01:20:30,026] {standard_task_runner.py:52} INFO - Started process 11180 to run task
[2021-08-21 01:20:30,031] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'creating_table', '2021-08-20T00:00:00+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmperg9r22f', '--error-file', '/tmp/tmpnldfsuff']
[2021-08-21 01:20:30,032] {standard_task_runner.py:77} INFO - Job 9: Subtask creating_table
[2021-08-21 01:20:30,085] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-08-20T00:00:00+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:20:30,157] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-08-20T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-20T00:00:00+00:00
[2021-08-21 01:20:30,157] {postgres.py:68} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        
[2021-08-21 01:20:30,170] {base.py:78} INFO - Using connection to: id: db_pg. Host: postgres, Port: None, Schema: ***, Login: ***, Password: ***, extra: {}
[2021-08-21 01:20:30,174] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        , parameters: None
[2021-08-21 01:20:30,175] {postgres.py:72} INFO - NOTICE:  relation "users" already exists, skipping

[2021-08-21 01:20:30,188] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=creating_table, execution_date=20210820T000000, start_date=20210821T012029, end_date=20210821T012030
[2021-08-21 01:20:30,233] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-21 01:20:30,280] {local_task_job.py:149} INFO - Task exited with return code 0
