[2021-08-21 01:25:41,468] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:39.186200+00:00 [queued]>
[2021-08-21 01:25:41,493] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:39.186200+00:00 [queued]>
[2021-08-21 01:25:41,493] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:41,494] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:25:41,494] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:41,504] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-21T01:25:39.186200+00:00
[2021-08-21 01:25:41,511] {standard_task_runner.py:52} INFO - Started process 11900 to run task
[2021-08-21 01:25:41,515] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-21T01:25:39.186200+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpoyqem884', '--error-file', '/tmp/tmpp8oz_4t7']
[2021-08-21 01:25:41,516] {standard_task_runner.py:77} INFO - Job 35: Subtask is_api_available
[2021-08-21 01:25:41,561] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:39.186200+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:25:41,628] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:25:39.186200+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:25:39.186200+00:00
[2021-08-21 01:25:41,629] {http.py:101} INFO - Poking: api/?nat=us,gb
[2021-08-21 01:25:41,643] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-21 01:25:41,646] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/?nat=us,gb
[2021-08-21 01:25:42,068] {base.py:248} INFO - Success criteria met. Exiting.
[2021-08-21 01:25:42,084] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210821T012539, start_date=20210821T012541, end_date=20210821T012542
[2021-08-21 01:25:42,167] {local_task_job.py:149} INFO - Task exited with return code 1
