[2021-08-21 01:25:28,361] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:26.638183+00:00 [queued]>
[2021-08-21 01:25:28,397] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:26.638183+00:00 [queued]>
[2021-08-21 01:25:28,397] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:28,397] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:25:28,397] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:25:28,412] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-21T01:25:26.638183+00:00
[2021-08-21 01:25:28,420] {standard_task_runner.py:52} INFO - Started process 11854 to run task
[2021-08-21 01:25:28,422] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-21T01:25:26.638183+00:00', '--job-id', '29', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp0olhpaq7', '--error-file', '/tmp/tmpxtw0n75m']
[2021-08-21 01:25:28,423] {standard_task_runner.py:77} INFO - Job 29: Subtask is_api_available
[2021-08-21 01:25:28,473] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-21T01:25:26.638183+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:25:28,524] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:25:26.638183+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:25:26.638183+00:00
[2021-08-21 01:25:28,525] {http.py:101} INFO - Poking: api/?nat=us,gb
[2021-08-21 01:25:28,539] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-21 01:25:28,540] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/?nat=us,gb
[2021-08-21 01:25:28,960] {base.py:248} INFO - Success criteria met. Exiting.
[2021-08-21 01:25:28,976] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210821T012526, start_date=20210821T012528, end_date=20210821T012528
[2021-08-21 01:25:29,034] {local_task_job.py:149} INFO - Task exited with return code 1
