[2021-08-21 01:21:37,619] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-21T01:21:36.225045+00:00 [queued]>
[2021-08-21 01:21:37,642] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.creating_table 2021-08-21T01:21:36.225045+00:00 [queued]>
[2021-08-21 01:21:37,643] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:21:37,643] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:21:37,643] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:21:37,654] {taskinstance.py:1107} INFO - Executing <Task(PostgresOperator): creating_table> on 2021-08-21T01:21:36.225045+00:00
[2021-08-21 01:21:37,659] {standard_task_runner.py:52} INFO - Started process 11357 to run task
[2021-08-21 01:21:37,664] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'creating_table', '2021-08-21T01:21:36.225045+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpfxb3utot', '--error-file', '/tmp/tmpb_yf05qm']
[2021-08-21 01:21:37,665] {standard_task_runner.py:77} INFO - Job 23: Subtask creating_table
[2021-08-21 01:21:37,717] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.creating_table 2021-08-21T01:21:36.225045+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:21:37,782] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=creating_table
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:21:36.225045+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:21:36.225045+00:00
[2021-08-21 01:21:37,782] {postgres.py:68} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        
[2021-08-21 01:21:37,790] {base.py:78} INFO - Using connection to: id: db_pg. Host: postgres, Port: None, Schema: ***, Login: ***, Password: ***, extra: {}
[2021-08-21 01:21:37,793] {dbapi.py:204} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL PRIMARY KEY
            );
        , parameters: None
[2021-08-21 01:21:37,794] {postgres.py:72} INFO - NOTICE:  relation "users" already exists, skipping

[2021-08-21 01:21:37,803] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=creating_table, execution_date=20210821T012136, start_date=20210821T012137, end_date=20210821T012137
[2021-08-21 01:21:37,846] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-08-21 01:21:37,873] {local_task_job.py:149} INFO - Task exited with return code 0
