[2021-08-21 01:21:38,795] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:21:36.225045+00:00 [queued]>
[2021-08-21 01:21:38,817] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-08-21T01:21:36.225045+00:00 [queued]>
[2021-08-21 01:21:38,817] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:21:38,817] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-21 01:21:38,817] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-21 01:21:38,827] {taskinstance.py:1107} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-08-21T01:21:36.225045+00:00
[2021-08-21 01:21:38,832] {standard_task_runner.py:52} INFO - Started process 11359 to run task
[2021-08-21 01:21:38,835] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-08-21T01:21:36.225045+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpcupr5rny', '--error-file', '/tmp/tmpeoda4x88']
[2021-08-21 01:21:38,836] {standard_task_runner.py:77} INFO - Job 24: Subtask is_api_available
[2021-08-21 01:21:38,886] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-08-21T01:21:36.225045+00:00 [running]> on host 07cd8e03eca8
[2021-08-21 01:21:38,963] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-08-21T01:21:36.225045+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-21T01:21:36.225045+00:00
[2021-08-21 01:21:38,964] {http.py:101} INFO - Poking: api/?nat=us,gb
[2021-08-21 01:21:38,979] {base.py:78} INFO - Using connection to: id: user_api. Host: https://randomuser.me/, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-08-21 01:21:38,981] {http.py:140} INFO - Sending 'GET' to url: https://randomuser.me/api/?nat=us,gb
[2021-08-21 01:21:39,378] {base.py:248} INFO - Success criteria met. Exiting.
[2021-08-21 01:21:39,392] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20210821T012136, start_date=20210821T012138, end_date=20210821T012139
[2021-08-21 01:21:39,448] {local_task_job.py:149} INFO - Task exited with return code 1
